app:
  image: graphdatabase_nodeserver:1     ## node.js v4

  links:            ## connects neo4j to app container
   - neo4j
  ports:            ## publish ports
   - "4000:4000"
  entrypoint: npm start   ## starts application

neo4j:
  image: neo4j:3.3          ## we use neo4j v3
  ports:                    ## publish ports to have Web UI
   - "7474:7474"
   - "7687:7687"
  volumes:                  ## adds folder with login/password
   - ./db/dbms:/data/dbms